apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: swiggy-v1  # Change to swiggy-v2 to route to green deployment
  ports:
    - port: 3000
      targetPort: 3000
``
